[[session]]
name = "_config/tmux"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "_config/zsh"
path = "~/.config/zshrc/"
startup_command = "nvim zshrc.conf"

[[session]]
name = "_config/nvim"
path = "~/.config/nvim/"
startup_command = "nvim"

